import '@/styles/globals.css'

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  UserButton,
} from '@clerk/nextjs'
import { Database } from 'lucide-react'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import { TRPCReactProvider } from '@/trpc/react'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider cookies={cookies().toString()}>
            <SignedOut>
              <div className="flex h-screen flex-1 items-center justify-center">
                <SignIn afterSignInUrl={'/'} />
              </div>
            </SignedOut>
            <SignedIn>
              <header className="sticky top-0 z-40 w-full border-b bg-background">
                <div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-10">
                  <div className="flex items-center justify-start gap-2">
                    <Database className="size-4" />
                    <span className="inline-block font-bold">DATASENSE</span>
                  </div>
                  <div className="flex gap-6 md:gap-10">
                    <UserButton />
                  </div>
                </div>
              </header>

              {children}
            </SignedIn>
          </TRPCReactProvider>
        </body>
      </ClerkProvider>
    </html>
  )
}
